/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cse_buffalo_resourceusage_BackgroundThread */

#ifndef _Included_com_cse_buffalo_resourceusage_BackgroundThread
#define _Included_com_cse_buffalo_resourceusage_BackgroundThread
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cse_buffalo_resourceusage_BackgroundThread
 * Method:    getMinors
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_com_cse_buffalo_resourceusage_BackgroundThread_getMinors
  (JNIEnv *, jobject);

/*
 * Class:     com_cse_buffalo_resourceusage_BackgroundThread
 * Method:    getReading
 * Signature: (I)Lcom/cse/buffalo/resourceusage/OutputTableRow;
 */
JNIEXPORT jobject JNICALL Java_com_cse_buffalo_resourceusage_BackgroundThread_getReading
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_cse_buffalo_resourceusage_BackgroundThread
 * Method:    getProcessName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cse_buffalo_resourceusage_BackgroundThread_getProcessName
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
